### ISSUE TITLE
Failed deployment Netlify

### ISSUE THREAD

**Issue by Pakillo** [SevillaR/SevillaRusers#1]
Hola @victorsuarezl

Ya está creado el repo, simplemente con un commit inicial con el tema hyde-hyde. También lo he enlazado a Netlify pero falla el deployment. Parece un error con el tema: https://app.netlify.com/sites/sevillarusers/deploys/5af223d28df89401f4e56a93. Pero ni idea

A ver si sabes qué puede ser. Ya tienes plenos poderes para manejarte aquí, así que a hacer todos los cambios que queráis!

gracias

**Comment by Pakillo** [comment]
Bueno, ya está resuelto (creo). Cambiando el hugo_version a 0.33 (que es la que yo tengo instalada). Ya al menos se ve algo en https://sevillarusers.netlify.com/ :)

No sé por qué no se ve igual que en mi ordenador. Pero bueno confío en vosotros para ponerlo bonito

**Comment by VictorSuarezL** [comment]
Genial! A ver si tengo un hueco y lo miro, subo la presentación y hago el post!
