### ISSUE TITLE
Is it possible to add RSS feeds?

### ISSUE THREAD

**Issue by Pakillo** [SevillaR/SevillaRusers#5]
Any idea @VictorSuarezL ?

**Comment by VictorSuarezL** [comment]
Not sure, may be [this helps](https://coolbutuseless.bitbucket.io/2018/02/07/blogdown-rss-feed-of-full-articles/). Academic theme also has a similar file `rss.xml` in layout folder, after adding this file the blog renders in locale without problem but I'm not sure if RSS feed works properly

**Comment by Pakillo** [comment]
Feeds are automatically generated and available at https://sevillarusers.netlify.com/index.xml. 
See https://gohugo.io/templates/rss/ & https://liao961120.github.io/2018/12/13/hugo_rss.html

Now only have to find out how to insert an icon or link to feed for people who want to subscribe
